# Generated by Django 5.0.1 on 2024-05-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_projectauth'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectauth',
            name='salt',
            field=models.CharField(default='salt', max_length=100),
        ),
    ]
